apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.master.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.master.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.master.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.master.name }}
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgresql-password
          ports:
            - containerPort: {{ .Values.postgres.master.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/postgresql
      volumes:
        - name: config-volume
          configMap:
            name: postgresql-config
            items:
              - key: master.conf
                path: postgresql.conf

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.slave.name }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.slave.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.slave.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.slave.name }}
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgresql-password
          ports:
            - containerPort: {{ .Values.postgres.slave.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/postgresql
      volumes:
        - name: config-volume
          configMap:
            name: postgresql-config
            items:
              - key: slave.conf
                path: postgresql.conf
