apiVersion: v2
name: akto-protection
description: Helm chart for installing Akto
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://www.akto.io
icon: https://akto-setup.s3.amazonaws.com/templates/128x128.png
sources:
  - https://github.com/akto-api-security/helm-charts/tree/master/charts/akto-protection
keywords:
  - akto
  - api
  - api security
  - dast
maintainers:
  - name: Ankush Jain
    email: ankush@akto.io
