apiVersion: v1
kind: Service
metadata:
  name: {{ include "akto.fullname" . }}-mini-runtime
  labels:
  {{- include "akto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mini_runtime.type }}
  selector:
    app: {{ include "akto.fullname" . }}-mini-runtime
  {{- include "akto.selectorLabels" . | nindent 4 }}
  ports:
  {{- if and .Values.mini_runtime.kafka1.useTls (not .Values.mini_runtime.data_ingestion.useIngestion) }}
  {{- .Values.ports.tls | toYaml | nindent 4 -}}
  {{- else if and .Values.mini_runtime.kafka1.useTls .Values.mini_runtime.data_ingestion.useIngestion }}
  {{- .Values.ports.dataIngestionWithTls | toYaml | nindent 4 -}}
  {{- else if .Values.mini_runtime.data_ingestion.useIngestion }}
  {{- .Values.ports.dataIngestion | toYaml | nindent 4 -}}
  {{- else }}
  {{- .Values.ports.default | toYaml | nindent 4 -}}
  {{- end }}
