apiVersion: v1
kind: Service
metadata:
  name: {{ include "akto.fullname" . }}-mini-runtime
  labels:
  {{- include "akto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mini_runtime.type }}
  selector:
    app: {{ include "akto.fullname" . }}-mini-runtime
  {{- include "akto.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mini_runtime.ports | toYaml | nindent 2 -}}