{{- if and .Values.mini_runtime.aktoApiSecurityRuntime.env.useSecretsForDatabaseAbstractorToken (not .Values.mini_runtime.aktoApiSecurityRuntime.env.databaseAbstractorTokenSecrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akto.fullname" . }}-mini-runtime
  labels:
  {{- include "akto.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.mini_runtime.aktoApiSecurityRuntime.env.databaseAbstractorTokenSecrets.token | toString | b64enc | quote }}
{{- end }}
