apiVersion: v1
kind: Service
metadata:
  name: {{ include "akto.fullname" . }}-mini-runtime
  labels:
  {{- include "akto.labels" . | nindent 4 }}
spec:
  ports:
  - name: kafka-9092
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: kafka-29092
    port: 29092
    targetPort: 29092
    protocol: TCP
  - name: kafka-19092
    port: 19092
    targetPort: 19092
    protocol: TCP
  - name: kafka-9999
    port: 9999
    targetPort: 9999
    protocol: TCP
  - name: zookeeper-2181
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: proxy-9091
    port: 9091
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ include "akto.fullname" . }}-mini-runtime
  {{- include "akto.selectorLabels" . | nindent 4 }}